In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
data = pd.read_csv('C:/Users/taham/Desktop/7th semester/AI by Sir Ayyaz/Assignments/train.csv')

In [3]:
data.head(2)

PassengerId  Survived  Pclass     Fare   Age  SibSp  Parch
0            1         0       3   7.2500  22.0      1      0
1            2         1       1  71.2833  38.0      1      0

In [4]:
X = (data[['PassengerId','Survived','Pclass','Fare','Age','SibSp','Parch']])

In [5]:
X[0:5]

PassengerId  Survived  Pclass     Fare   Age  SibSp  Parch
0            1         0       3   7.2500  22.0      1      0
1            2         1       1  71.2833  38.0      1      0
2            3         1       3   7.9250  26.0      0      0
3            4         1       1  53.1000  35.0      1      0
4            5         0       3   8.0500  35.0      0      0

In [6]:
Y = np.array(data[['Survived']])

In [7]:
Y[0:1]

array([[0]], dtype=int64)

In [9]:
# cols = ['PassengerId','Survived','Pclass','Fare','Age','SibSp','Parch']
# X_new = x[cols]
# X_new.head(2)

In [10]:
X_new = X_new[cols].apply( lambda rec:(rec - rec.mean())/rec.std(), axis =0)

NameError: name 'X_new' is not defined

In [288]:
type(X_new)

pandas.core.frame.DataFrame

In [289]:
X_new.head(10)
list(X_new)

['PassengerId', 'Survived', 'Pclass', 'Fare', 'Age', 'SibSp', 'Parch']

In [290]:
X_new = np.array(X_new)
X_new[0:3]

array([[-1.7291368 , -0.7888293 ,  0.82691282, -0.50216314, -0.5300051 ,
         0.43255043, -0.47340772],
       [-1.7252511 ,  1.26627861, -1.56522783,  0.78640362,  0.57143041,
         0.43255043, -0.47340772],
       [-1.7213654 ,  1.26627861,  0.82691282, -0.48857985, -0.25464622,
        -0.47427882, -0.47340772]])

In [ ]:
# randomly initializing the beta cooficient

In [291]:
import random

In [292]:
def initialize_betas(dim):
    b = random.random()
    w = np.random.rand(dim)
    return b,w 

In [293]:
b,w = initialize_betas(X_new.shape[0])
print(b,w)

0.6767864613033776 [0.23281067 0.55794112 0.25230205 0.57661457 0.51299632 0.26553547
 0.83332498 0.24382112 0.35889982 0.53629192 0.59610539 0.04959972
 0.89250644 0.81759676 0.93150489 0.72202956 0.61522925 0.90096327
 0.79160186 0.92540155 0.08044368 0.54494752 0.55310557 0.66154716
 0.47432139 0.29894738 0.15693716 0.13730472 0.45993279 0.20749681
 0.43917372 0.05506516 0.36878948 0.14780752 0.26778668 0.72726473
 0.56807703 0.16673652 0.00848848 0.18724736 0.64856419 0.78793792
 0.11550074 0.43737905 0.53310926 0.83900714 0.21662558 0.92587285
 0.82211295 0.75629674 0.32653436 0.49314412 0.32950655 0.49756549
 0.6801587  0.70755955 0.7709435  0.82806003 0.23259661 0.18796091
 0.04913409 0.32871467 0.60560548 0.52903572 0.81611769 0.76550998
 0.92913059 0.6090762  0.06000307 0.93834438 0.64787279 0.07312417
 0.2185201  0.49485573 0.05708611 0.22318205 0.23083698 0.23734695
 0.29083162 0.23257803 0.46627517 0.32610019 0.84314262 0.59329625
 0.4114576  0.66043651 0.47868605 0.8637246

In [294]:
w.shape

(891,)

In [295]:
type(w)

numpy.ndarray

In [ ]:
# Define a sigmoid func to predict Y

In [299]:
def sigmoid(b,w,X_new):
    z = b+np.matmul(X_new,w)
    return (1.0 / (1+ np.exp(-z)))

In [300]:
y_not = sigmoid(b,w,X_new)
y_not[0:4]

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 891 is different from 7)

In [268]:
Y[0:4]

array([0, 1, 1, 1], dtype=int64)

In [1]:
def cost(Y, y_not):
    return - np.sum(np.dot(y.T,np.log(1-y_not)+ np.dot((1-y).T,np.log(1-y_not)))) / ( len(y))

In [3]:
# Reshape Y
Y=Y.reshape(len(Y), )
current_cost= cost(Y,y_not)
#print(current_cost)
Y.shape

NameError: name 'Y' is not defined

In [101]:
# defining function for update beta values

In [271]:
def update_beta(b0,w0,y,y_not,X_new, alpha):
    db = np.sum(y_not-y)/len(y)
    b0 = b0- alpha*db
    dw = np.dot((y_not-y),X_new)/len(y)
    w0 = w0- alpha+dw
    
    return b0,w0

In [256]:
alpha = 0.1
# type(y_not)
# (X_new).shape

In [272]:
update_beta(b,w,Y,y_not,X_new,alpha)

ValueError: operands could not be broadcast together with shapes (891,) (199,) 

In [207]:
b.shape

()

In [174]:
w.shape

(7,)

In [175]:
print(b,w)

nan [nan nan nan nan nan nan nan]


In [149]:
# code for gradient descent

In [211]:
num_iterations = 500
alpha = 0.00005

all_costs = []
b,w = initialize_betas(X_new.shape[0])
print("initial guess of b and w: " , b ,w)

for each_iter in range (num_iterations ):
    y_not = sigmoid(b, w , X_new)
    current_cost = cost (Y, y_not)
    prev_b = b
    prev_w = w
    b, w = update_beta (prev_b, prev_w, Y, y_not, X_new, alpha)
    all_costs.append(current_cost)
    if each_iter % 10 == 0:
        print('Iteration: ', each_iter, 'Cost: ', current_cost)
        each_iter += 1
    
#print('b_0:', b_0, 'b_1:',b_1,'b_2:',b_2,'b_3:',b_3,'b_4:', b_4, 'b_5:',b_5,'b_6:',b_6,'b_7:',b_7,'b_8:',b_8,'b_9:',b_9)
print("Final estimates of b and q are: ", b,w)

initial guess of b and w:  0.7466806841242318 [1.90870771e-01 8.06466366e-01 6.04213093e-01 5.47905074e-01
 3.88624470e-01 1.26070550e-01 1.90643038e-02 9.12431196e-02
 5.31277683e-01 2.07689038e-01 6.81770008e-01 5.33864170e-01
 4.25424806e-01 2.60816279e-01 6.96132206e-01 2.01133752e-01
 1.84973478e-01 9.65672299e-01 8.10903288e-01 8.78719767e-01
 6.48440859e-01 3.90939502e-02 7.41241409e-01 8.87939347e-01
 6.21113423e-01 5.37882285e-01 2.47764693e-02 3.82899165e-01
 8.32583589e-01 8.06402308e-01 1.70394707e-02 8.46025302e-01
 1.45083081e-01 2.52884216e-01 5.68723216e-01 5.10659823e-01
 8.45149644e-01 8.65930301e-01 8.28733302e-01 6.47348087e-03
 7.24361956e-01 3.95177166e-01 4.02837077e-01 8.06740272e-01
 2.53607233e-01 3.68854873e-01 4.01886188e-01 7.46546782e-01
 3.30302269e-01 7.40781623e-01 7.95871324e-01 3.71879690e-01
 3.14769353e-01 8.12989381e-01 5.57086600e-01 5.30779218e-02
 5.07065605e-01 3.70071326e-02 8.40939296e-01 2.41554003e-01
 2.27307472e-01 4.92077264e-01 1.869468

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 891 is different from 7)

In [176]:
# Use sklearn logistic regression

In [178]:
from sklearn.linear_model import LogisticRegression

lreg = LogisticRegression()
lmodel = lreg.fit(X_new, Y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [1]:
print(1,10)

1 10
